version: "3.9"

services:
  pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    image: ylianach/copypaste:latest
    container_name: pastebin
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    driver: bridge

